"""GSC CLI — durable, browser-free Google Search Console automation for mingxinstorage.xyz.

Pure standard library (no pip installs). Uses Google OAuth 2.0 "installed app"
(loopback) flow once, caches a refresh token locally, then calls the Search
Console REST API headlessly thereafter.

What this DOES cover (official API, durable):
  - sites        : list verified properties on the account
  - sitemaps     : list submitted sitemaps for a property
  - submit-sitemap : (PUT) submit / resubmit a sitemap feed
  - inspect      : URL Inspection (read-only index status of a page)
  - inspect-batch: inspect many URLs (from sitemap or a file) -> JSON report
  - analytics    : Search Analytics query (clicks / impressions / position / queries)

What this does NOT cover (Google restriction, not ours):
  - "Request Indexing" (请求编入索引) has NO public API. Google's Indexing API
    only supports JobPosting / BroadcastEvent pages, not general web pages.
    That daily action must be done in the browser (see README / browser session).

Security:
  - We never store your Google password. OAuth stores only a refresh token.
  - Client secret + token live under seo_geo_loop/secrets/ which is gitignored.

Setup (one-time, ~3 min): see `python gsc_cli.py setup-help`.
"""
from __future__ import annotations

import argparse
import http.server
import json
import os
import secrets as _secrets
import sys
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
import webbrowser
import xml.etree.ElementTree as ET
from datetime import datetime, timedelta, timezone
from pathlib import Path

try:  # make Chinese output safe on Windows consoles
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
except Exception:  # noqa: BLE001
    pass

# --------------------------------------------------------------------------- #
# Paths & constants
# --------------------------------------------------------------------------- #
ROOT = Path(__file__).resolve().parent
SECRETS = ROOT / "secrets"
CLIENT_FILE = SECRETS / "gsc_oauth_client.json"   # you provide (downloaded from Google Cloud)
TOKEN_FILE = SECRETS / "gsc_token.json"           # generated by `auth`
OUT_DIR = ROOT / "outputs"

HOST = os.environ.get("MX_SITE_HOST", "mingxinstorage.xyz")
DEFAULT_SITE = f"sc-domain:{HOST}"
SITEMAP_URL = f"https://{HOST}/sitemap.xml"

# webmasters scope allows both read and sitemap submit.
SCOPE = "https://www.googleapis.com/auth/webmasters"
AUTH_ENDPOINT = "https://accounts.google.com/o/oauth2/v2/auth"
TOKEN_ENDPOINT = "https://oauth2.googleapis.com/token"
API = "https://searchconsole.googleapis.com"

_UA = f"Mingxin-GSC-CLI/1.0 (+https://{HOST}/)"


# --------------------------------------------------------------------------- #
# Low-level HTTP helpers
# --------------------------------------------------------------------------- #
def _request(method: str, url: str, *, headers: dict | None = None,
             data: bytes | None = None, timeout: int = 45) -> tuple[int, str]:
    req = urllib.request.Request(url, data=data, method=method,
                                 headers={"User-Agent": _UA, **(headers or {})})
    try:
        r = urllib.request.urlopen(req, timeout=timeout)
        return r.status, r.read().decode("utf-8", "ignore")
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode("utf-8", "ignore")
    except Exception as e:  # noqa: BLE001
        return -1, f"{type(e).__name__}: {e}"


def _post_form(url: str, form: dict, timeout: int = 45) -> tuple[int, dict]:
    body = urllib.parse.urlencode(form).encode()
    st, txt = _request("POST", url, headers={"Content-Type": "application/x-www-form-urlencoded"},
                       data=body, timeout=timeout)
    try:
        return st, json.loads(txt) if txt else {}
    except json.JSONDecodeError:
        return st, {"raw": txt}


def _api(method: str, path: str, token: str, *, payload: dict | None = None) -> tuple[int, dict]:
    data = json.dumps(payload).encode() if payload is not None else None
    headers = {"Authorization": f"Bearer {token}"}
    if data is not None:
        headers["Content-Type"] = "application/json; charset=utf-8"
    st, txt = _request(method, f"{API}{path}", headers=headers, data=data)
    try:
        return st, (json.loads(txt) if txt else {})
    except json.JSONDecodeError:
        return st, {"raw": txt}


# --------------------------------------------------------------------------- #
# OAuth: client config + token cache + refresh
# --------------------------------------------------------------------------- #
def _load_client() -> dict:
    if not CLIENT_FILE.exists():
        sys.exit(f"[!] Missing {CLIENT_FILE}.\n    Run: python gsc_cli.py setup-help")
    raw = json.loads(CLIENT_FILE.read_text(encoding="utf-8"))
    node = raw.get("installed") or raw.get("web") or raw
    cid, csec = node.get("client_id"), node.get("client_secret")
    if not cid or not csec:
        sys.exit(f"[!] {CLIENT_FILE} has no client_id/client_secret. Re-download the OAuth Desktop client.")
    return {"client_id": cid, "client_secret": csec}


def _save_token(tok: dict) -> None:
    SECRETS.mkdir(parents=True, exist_ok=True)
    TOKEN_FILE.write_text(json.dumps(tok, ensure_ascii=False, indent=2), encoding="utf-8")


def _access_token() -> str:
    """Return a valid access token, refreshing via the cached refresh token."""
    if not TOKEN_FILE.exists():
        sys.exit("[!] Not authorized yet. Run: python gsc_cli.py auth")
    tok = json.loads(TOKEN_FILE.read_text(encoding="utf-8"))
    # reuse cached access token if still valid (60s safety margin)
    exp = tok.get("expires_at", 0)
    if tok.get("access_token") and exp - 60 > time.time():
        return tok["access_token"]
    cl = _load_client()
    st, data = _post_form(TOKEN_ENDPOINT, {
        "client_id": cl["client_id"],
        "client_secret": cl["client_secret"],
        "refresh_token": tok["refresh_token"],
        "grant_type": "refresh_token",
    })
    if st != 200 or "access_token" not in data:
        sys.exit(f"[!] Token refresh failed ({st}): {data}\n    Re-run: python gsc_cli.py auth")
    tok["access_token"] = data["access_token"]
    tok["expires_at"] = time.time() + int(data.get("expires_in", 3600))
    _save_token(tok)
    return tok["access_token"]


class _CodeHandler(http.server.BaseHTTPRequestHandler):
    code: str | None = None
    state: str | None = None

    def do_GET(self):  # noqa: N802
        q = urllib.parse.urlparse(self.path).query
        params = urllib.parse.parse_qs(q)
        _CodeHandler.code = (params.get("code") or [None])[0]
        _CodeHandler.state = (params.get("state") or [None])[0]
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.end_headers()
        ok = bool(_CodeHandler.code)
        msg = ("授权成功，可以关闭此页面并回到 Cursor。" if ok
               else "未收到授权码，请重试。")
        self.wfile.write(f"<html><body style='font-family:sans-serif;padding:40px'>"
                         f"<h2>{'✅' if ok else '⚠️'} {msg}</h2></body></html>".encode())

    def log_message(self, *_):  # silence
        return


def cmd_auth(_args) -> int:
    cl = _load_client()
    state = _secrets.token_urlsafe(16)
    # bind a loopback port
    server = http.server.HTTPServer(("127.0.0.1", 0), _CodeHandler)
    port = server.server_address[1]
    redirect_uri = f"http://127.0.0.1:{port}/"
    auth_url = AUTH_ENDPOINT + "?" + urllib.parse.urlencode({
        "client_id": cl["client_id"],
        "redirect_uri": redirect_uri,
        "response_type": "code",
        "scope": SCOPE,
        "access_type": "offline",
        "prompt": "consent",
        "state": state,
    })
    print("\n=== 一次性授权 ===")
    print("1) 在浏览器打开下面这个链接并用 mingxinstorage.xyz 的 GSC 账号同意授权：\n")
    print(auth_url + "\n")
    print(f"   (本地回调端口: {port}；授权后会自动跳回并被本工具捕获)")
    try:
        webbrowser.open(auth_url)
    except Exception:  # noqa: BLE001
        pass

    th = threading.Thread(target=server.handle_request, daemon=True)
    th.start()
    print("\n等待授权回调中（最多 300 秒）...")
    th.join(timeout=300)
    server.server_close()

    if not _CodeHandler.code:
        sys.exit("[!] 未捕获到授权码（超时或被拒绝）。请重试 auth。")
    if _CodeHandler.state != state:
        sys.exit("[!] state 校验失败，已中止（防 CSRF）。请重试 auth。")

    st, data = _post_form(TOKEN_ENDPOINT, {
        "client_id": cl["client_id"],
        "client_secret": cl["client_secret"],
        "code": _CodeHandler.code,
        "grant_type": "authorization_code",
        "redirect_uri": redirect_uri,
    })
    if st != 200 or "refresh_token" not in data:
        sys.exit(f"[!] 兑换令牌失败 ({st}): {data}\n"
                 f"    提示：若没有 refresh_token，请到账号的“第三方访问权限”移除旧授权后重试 auth。")
    tok = {
        "refresh_token": data["refresh_token"],
        "access_token": data.get("access_token"),
        "expires_at": time.time() + int(data.get("expires_in", 3600)),
        "scope": data.get("scope", SCOPE),
        "authorized_at": datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds"),
    }
    _save_token(tok)
    print(f"\n[OK] 授权完成，已缓存刷新令牌到 {TOKEN_FILE}")
    print("     之后所有命令都无需再次登录（除非你主动撤销授权）。")
    return 0


# --------------------------------------------------------------------------- #
# Commands
# --------------------------------------------------------------------------- #
def _site_path(site: str) -> str:
    return urllib.parse.quote(site, safe="")


def cmd_sites(_args) -> int:
    st, data = _api("GET", "/webmasters/v3/sites", _access_token())
    if st != 200:
        sys.exit(f"[!] sites failed ({st}): {data}")
    entries = data.get("siteEntry", [])
    print(f"已验证属性 ({len(entries)}):")
    for e in entries:
        print(f"  - {e.get('siteUrl')}   [{e.get('permissionLevel')}]")
    return 0


def cmd_sitemaps(args) -> int:
    st, data = _api("GET", f"/webmasters/v3/sites/{_site_path(args.site)}/sitemaps", _access_token())
    if st != 200:
        sys.exit(f"[!] sitemaps failed ({st}): {data}")
    sms = data.get("sitemap", [])
    print(f"{args.site} 已提交 sitemap ({len(sms)}):")
    for s in sms:
        cont = s.get("contents", [{}])
        n = cont[0].get("submitted") if cont else "?"
        print(f"  - {s.get('path')}  | 上次下载: {s.get('lastDownloaded','-')} | "
              f"errors: {s.get('errors','0')} warnings: {s.get('warnings','0')} | submitted: {n}")
    return 0


def cmd_submit_sitemap(args) -> int:
    feed = args.feed or SITEMAP_URL
    path = f"/webmasters/v3/sites/{_site_path(args.site)}/sitemaps/{urllib.parse.quote(feed, safe='')}"
    st, data = _api("PUT", path, _access_token())
    if st in (200, 204):
        print(f"[OK] 已提交 sitemap: {feed}  (site={args.site})")
        return 0
    sys.exit(f"[!] submit-sitemap failed ({st}): {data}")


def _inspect_one(site: str, url: str, token: str) -> dict:
    st, data = _api("POST", "/v1/urlInspection/index:inspect", token, payload={
        "inspectionUrl": url, "siteUrl": site, "languageCode": "zh-CN",
    })
    if st != 200:
        return {"url": url, "ok": False, "http": st, "error": data}
    res = (data.get("inspectionResult") or {}).get("indexStatusResult", {})
    return {
        "url": url,
        "ok": True,
        "verdict": res.get("verdict"),                 # PASS / NEUTRAL / FAIL
        "coverageState": res.get("coverageState"),     # e.g. 'Submitted and indexed'
        "robotsTxtState": res.get("robotsTxtState"),
        "indexingState": res.get("indexingState"),
        "lastCrawlTime": res.get("lastCrawlTime"),
        "pageFetchState": res.get("pageFetchState"),
        "googleCanonical": res.get("googleCanonical"),
    }


def cmd_inspect(args) -> int:
    out = _inspect_one(args.site, args.url, _access_token())
    print(json.dumps(out, ensure_ascii=False, indent=2))
    return 0 if out.get("ok") else 1


def _sitemap_urls() -> list[str]:
    st, txt = _request("GET", SITEMAP_URL)
    urls: list[str] = []
    if st == 200:
        try:
            root = ET.fromstring(txt)
            for loc in root.iter():
                if loc.tag.endswith("loc") and loc.text:
                    urls.append(loc.text.strip())
        except ET.ParseError:
            pass
    return sorted(set(urls))


def cmd_inspect_batch(args) -> int:
    if args.file:
        urls = [ln.strip() for ln in Path(args.file).read_text(encoding="utf-8").splitlines()
                if ln.strip() and not ln.startswith("#")]
    else:
        urls = _sitemap_urls()
    if args.limit:
        urls = urls[: args.limit]
    if not urls:
        sys.exit("[!] 没有可检查的 URL（sitemap 为空或文件为空）。")
    token = _access_token()
    rows, summary = [], {}
    print(f"批量检查 {len(urls)} 个 URL ...")
    for i, u in enumerate(urls, 1):
        r = _inspect_one(args.site, u, token)
        rows.append(r)
        key = r.get("coverageState") or r.get("error", {}).get("error", {}).get("status") or r.get("verdict") or "UNKNOWN"
        summary[key] = summary.get(key, 0) + 1
        print(f"  [{i}/{len(urls)}] {r.get('coverageState') or r.get('verdict') or r.get('http')}  {u}")
        time.sleep(0.4)  # gentle on quota
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUT_DIR / "gsc_inspect_batch.json"
    out.write_text(json.dumps({
        "site": args.site,
        "checked_at": datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds"),
        "count": len(rows), "summary": summary, "rows": rows,
    }, ensure_ascii=False, indent=2), encoding="utf-8")
    print("\n汇总:", json.dumps(summary, ensure_ascii=False))
    print(f"[OK] 明细写入 {out}")
    return 0


def cmd_analytics(args) -> int:
    end = datetime.now(timezone.utc).date()
    start = end - timedelta(days=args.days)
    payload = {
        "startDate": start.isoformat(),
        "endDate": end.isoformat(),
        "dimensions": args.dimensions.split(",") if args.dimensions else ["query"],
        "rowLimit": args.limit,
    }
    st, data = _api("POST", f"/webmasters/v3/sites/{_site_path(args.site)}/searchAnalytics/query",
                    _access_token(), payload=payload)
    if st != 200:
        sys.exit(f"[!] analytics failed ({st}): {data}")
    rows = data.get("rows", [])
    print(f"{args.site}  {start}~{end}  维度={payload['dimensions']}  共 {len(rows)} 行")
    for r in rows:
        keys = " | ".join(r.get("keys", []))
        print(f"  {keys:<50}  clicks={r.get('clicks',0):<6} imp={r.get('impressions',0):<7} "
              f"ctr={r.get('ctr',0)*100:.1f}% pos={r.get('position',0):.1f}")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "gsc_analytics.json").write_text(
        json.dumps({"site": args.site, "range": [start.isoformat(), end.isoformat()],
                    "payload": payload, "rows": rows}, ensure_ascii=False, indent=2), encoding="utf-8")
    return 0


PROPERTIES_FILE = OUT_DIR / "gsc_properties.json"


def _load_domains() -> list[str]:
    if not PROPERTIES_FILE.exists():
        sys.exit(f"[!] 缺少属性清单 {PROPERTIES_FILE}（应包含 domains 数组）。")
    data = json.loads(PROPERTIES_FILE.read_text(encoding="utf-8"))
    domains = data.get("domains") or []
    if not domains:
        sys.exit(f"[!] {PROPERTIES_FILE} 的 domains 为空。")
    return domains


def _is_live(domain: str) -> tuple[bool, int]:
    """Cheap liveness probe for https://<domain>/ (HEAD-ish via GET)."""
    st, _ = _request("GET", f"https://{domain}/", timeout=15)
    return (200 <= st < 400), st


def cmd_submit_sitemap_all(args) -> int:
    domains = _load_domains()
    token = _access_token()
    feed_path = args.feed_path.lstrip("/")
    rows, summary = [], {}
    print(f"对 {len(domains)} 个域名属性提交 sitemap (/{feed_path}) ...")
    for i, d in enumerate(domains, 1):
        site = f"sc-domain:{d}"
        feed = f"https://{d}/{feed_path}"
        if args.check_live:
            live, code = _is_live(d)
            if not live:
                rows.append({"domain": d, "submitted": False, "reason": f"home not live ({code})"})
                summary["skipped_not_live"] = summary.get("skipped_not_live", 0) + 1
                print(f"  [{i}/{len(domains)}] skip {d} (home {code})")
                continue
        path = f"/webmasters/v3/sites/{_site_path(site)}/sitemaps/{urllib.parse.quote(feed, safe='')}"
        st, data = _api("PUT", path, token)
        ok = st in (200, 204)
        rows.append({"domain": d, "submitted": ok, "http": st, "feed": feed,
                     "error": None if ok else data})
        key = "submitted" if ok else f"http_{st}"
        summary[key] = summary.get(key, 0) + 1
        print(f"  [{i}/{len(domains)}] {'OK ' if ok else 'ERR'} {d}  ({st})")
        time.sleep(args.sleep)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUT_DIR / "gsc_submit_sitemap_all.json"
    out.write_text(json.dumps({
        "feed_path": feed_path, "check_live": args.check_live,
        "ran_at": datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds"),
        "count": len(rows), "summary": summary, "rows": rows,
    }, ensure_ascii=False, indent=2), encoding="utf-8")
    print("\n汇总:", json.dumps(summary, ensure_ascii=False))
    print(f"[OK] 明细写入 {out}")
    return 0


def cmd_inspect_home_all(args) -> int:
    domains = _load_domains()
    token = _access_token()
    if args.limit:
        domains = domains[: args.limit]
    rows, summary = [], {}
    print(f"检查 {len(domains)} 个域名首页收录状态 ...")
    for i, d in enumerate(domains, 1):
        site = f"sc-domain:{d}"
        r = _inspect_one(site, f"https://{d}/", token)
        r["domain"] = d
        rows.append(r)
        key = r.get("coverageState") or r.get("verdict") or (r.get("error", {}) or {}).get("error", {}).get("status") or "UNKNOWN"
        summary[key] = summary.get(key, 0) + 1
        print(f"  [{i}/{len(domains)}] {r.get('coverageState') or r.get('verdict') or r.get('http')}  {d}")
        time.sleep(args.sleep)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUT_DIR / "gsc_inspect_home_all.json"
    out.write_text(json.dumps({
        "ran_at": datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds"),
        "count": len(rows), "summary": summary, "rows": rows,
    }, ensure_ascii=False, indent=2), encoding="utf-8")
    print("\n汇总:", json.dumps(summary, ensure_ascii=False))
    print(f"[OK] 明细写入 {out}")
    return 0


def cmd_setup_help(_args) -> int:
    print(SETUP_HELP)
    return 0


SETUP_HELP = """\
=== GSC CLI 一次性配置（约 3 分钟，只需做一次）===

目标：拿到一份 OAuth「桌面应用」客户端 JSON，放到 secrets/ 下，然后运行 auth。

1) 打开 Google Cloud Console（用 mingxinstorage.xyz 的 GSC 同一个谷歌账号）：
   https://console.cloud.google.com/
   - 新建（或选择）一个项目。

2) 启用 Search Console API：
   https://console.cloud.google.com/apis/library/searchconsole.googleapis.com
   - 点「启用 / Enable」。

3) 配置 OAuth 同意屏幕（OAuth consent screen）：
   - User Type 选「外部 / External」即可；填应用名、你的邮箱。
   - 「测试用户 / Test users」里把 REDACTED_GOOGLE_ACCOUNT 加进去（关键，否则授权会被拦）。

4) 创建凭据 → OAuth 客户端 ID：
   https://console.cloud.google.com/apis/credentials
   - 应用类型选「桌面应用 / Desktop app」。
   - 创建后点「下载 JSON」。

5) 把下载的 JSON 重命名放到：
   seo_geo_loop/secrets/gsc_oauth_client.json

6) 运行授权（会弹出/打印一个链接，用浏览器同意一次）：
   python gsc_cli.py auth

7) 验证：
   python gsc_cli.py sites
   python gsc_cli.py sitemaps
   python gsc_cli.py inspect https://mingxinstorage.xyz/products

之后这些命令都无需再登录。secrets/ 已被 gitignore，不会进版本库。

注意：本工具不含「请求编入索引」——谷歌没有对应公开 API，那个动作只能在浏览器里点。
"""


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="GSC CLI — browser-free Search Console automation for mingxinstorage.xyz")
    p.add_argument("--site", default=DEFAULT_SITE, help=f"property (default: {DEFAULT_SITE})")
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("setup-help", help="打印一次性配置指南").set_defaults(func=cmd_setup_help)
    sub.add_parser("auth", help="一次性 OAuth 授权（之后免登录）").set_defaults(func=cmd_auth)
    sub.add_parser("sites", help="列出账号下已验证属性").set_defaults(func=cmd_sites)
    sub.add_parser("sitemaps", help="列出该属性已提交的 sitemap").set_defaults(func=cmd_sitemaps)

    sp = sub.add_parser("submit-sitemap", help="提交/重提 sitemap")
    sp.add_argument("--feed", default=None, help=f"sitemap URL (default: {SITEMAP_URL})")
    sp.set_defaults(func=cmd_submit_sitemap)

    ip = sub.add_parser("inspect", help="单个 URL 收录状态（只读）")
    ip.add_argument("url")
    ip.set_defaults(func=cmd_inspect)

    ib = sub.add_parser("inspect-batch", help="批量收录状态 -> outputs/gsc_inspect_batch.json")
    ib.add_argument("--file", default=None, help="URL 列表文件（默认读线上 sitemap.xml）")
    ib.add_argument("--limit", type=int, default=0, help="最多检查多少个（0=全部）")
    ib.set_defaults(func=cmd_inspect_batch)

    an = sub.add_parser("analytics", help="搜索表现数据")
    an.add_argument("--days", type=int, default=28)
    an.add_argument("--dimensions", default="query", help="逗号分隔: query,page,country,device,date")
    an.add_argument("--limit", type=int, default=25)
    an.set_defaults(func=cmd_analytics)

    # ---- 全账号批量（读 outputs/gsc_properties.json 的 222 个域名）----
    sa = sub.add_parser("submit-sitemap-all", help="对清单内所有域名属性批量提交 sitemap")
    sa.add_argument("--feed-path", default="sitemap.xml", help="sitemap 相对路径（默认 sitemap.xml）")
    sa.add_argument("--check-live", action="store_true", help="先探测首页存活，跳过未上线的站点")
    sa.add_argument("--sleep", type=float, default=0.5, help="每站间隔秒数")
    sa.set_defaults(func=cmd_submit_sitemap_all)

    ia = sub.add_parser("inspect-home-all", help="批量检查清单内所有域名首页的收录状态")
    ia.add_argument("--limit", type=int, default=0, help="最多检查多少个（0=全部）")
    ia.add_argument("--sleep", type=float, default=0.4, help="每站间隔秒数")
    ia.set_defaults(func=cmd_inspect_home_all)
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
